### ISSUE TITLE
Fails if object property is a Javascript Date object

### ISSUE THREAD

**Issue by joelkoz** [jonschlinkert/omit-deep#4]
If an object property is a javascript Date object and it is NOT to be omitted, the value is transformed to an empty object ({}) vs. retaining its date value.

Looking deeper, all non-omitted properties that are objects lose their prototype chains and thus their true type. This implementation is thus best used for simple JSON type objects like data objects and not typed object graphs where members have objects with constructors.

**Comment by jonschlinkert** [comment]
Good points, I think we should be checking for a plain object, not just an object.
